### ISSUE TITLE
Problem s referencemi

### ISSUE THREAD

**Issue by Semtexcz** [Narodni-repozitar/nr-oai-pmh-harvester#1]
16504. Record, OAI ID: 'oai:invenio.nusl.cz:19456'
Traceback (most recent call last):
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/oarepo/oarepo-oai-pmh-harvester/oarepo_oai_pmh_harvester/synchronization.py", line 216, in record_handling
    self.record_crud(oai_rec, timestamp=datestamp, deleted=deleted, idx=idx,
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/oarepo/oarepo-oai-pmh-harvester/oarepo_oai_pmh_harvester/synchronization.py", line 252, in record_crud
    self.create_or_update(oai_identifier, timestamp, oai_rec=oai_rec, xml=xml)
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/oarepo/oarepo-oai-pmh-harvester/oarepo_oai_pmh_harvester/synchronization.py", line 326, in create_or_update
    record, pid = self.create_record(transformed)
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/oarepo/oarepo-oai-pmh-harvester/oarepo_oai_pmh_harvester/synchronization.py", line 378, in create_record
    record = record_class.create(data, id_=pid.object_uuid)
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/repo/nr-oai-pmh-harvester/venv/lib/python3.8/site-packages/oarepo_validate/record.py", line 141, in create
    ret = super().create(data, id_, **kwargs)
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/repo/nr-oai-pmh-harvester/venv/lib/python3.8/site-packages/invenio_records/api.py", line 187, in create
    after_record_insert.send(
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/repo/nr-oai-pmh-harvester/venv/lib/python3.8/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/repo/nr-oai-pmh-harvester/venv/lib/python3.8/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/home/semtex/GoogleDrive/Projekty/Pracovní/repo/nr-oai-pmh-harvester/venv/lib/python3.8/site-packages/oarepo_references/signals.py", line 49, in create_references_record
    assert record.oarepo_references is not None, \
AttributeError: 'PublishedEventRecordDraft' object has no attribute 'oarepo_references'

**Comment by Semtexcz** [comment]
Vyřešeno aktualizací na nové oarepo-references a oarepo-taxonomies
